services:
  - type: web
    name: entreprenapp-backend
    env: node
    plan: standard
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: entreprenapp-web
    env: node
    plan: standard
    buildCommand: cd entreprenapp-frontend && npm install && npm run build
    startCommand: cd entreprenapp-frontend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://entreprenapp-backend-byvn.onrender.com
      - key: VITE_SOCKET_URL
        value: https://entreprenapp-backend-byvn.onrender.com
    routes:
      - path: /*
        destination: /

