services:
  - type: static_site
    name: entrepreneurapp-frontend
    rootDir: entrepreneurapp-frontend
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://entreprenapp-backend-byvn.onrender.com/api
      - key: VITE_SOCKET_URL
        value: https://entreprenapp-backend-byvn.onrender.com
