services:
  - type: web
    name: entreprenapp-backend
    env: node
    plan: standard
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

