services:
  - type: web
    name: entreprenapp-backend
    env: node
    plan: standard
    buildCommand: cd /opt/render/project/src && node build.js
    startCommand: cd /opt/render/project/src && node start.js
    envVars:
      - key: NODE_ENV
        value: production

