services:
  - type: static
    name: entrepreneurapp-frontend
    rootDir: entrepreneurapp-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
