services:
  - type: web
    name: entreprenapp-backend
    env: node
    plan: standard
    buildCommand: node build.js
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production

